// src/pages/Home/index.tsx
// import react, { useState } from 'react';
import { Paragraph } from '../../components/Typography/styles';
import { Skills } from "./styles";

import MainResume from '../../components/Sections/MainResume';
import { FlexLayoutRow } from "../../components/FlexLayout";

import { Card } from '../../components/Card';

import { StyledLink } from '../../components/ButtonLink';


import path_SkillJS from "../../assets/images/JS.png";
import path_SkillIHC from "../../assets/images/IHC.png";

function Home(){
    return(
        <>
            <FlexLayoutRow>
                <MainResume className="michelcamargo"/>
            </FlexLayoutRow>

            <FlexLayoutRow>
                <StyledLink to={'https://www.linkedin.com/in/michelscamargo/'} color="#FFF" bgColor={"#0A66C2"} target={"_blank"}>
                    LinkedIn
                </StyledLink>
            </FlexLayoutRow>


            {/*<FlexLayoutRow>*/}

            {/*    /!*<ExtButton2 width='150px' to='https://www.linkedin.com/in/michelscamargo/' bgColor='var(--white)' color='#555' target="_blank">LinkedIn</ExtButton2>*!/*/}

            {/*    <Skills>*/}
            {/*        <Card title="Web Development" textColor="#222" bgColor="#FFF" srcImage={path_SkillJS} >*/}
            {/*            <Paragraph>*/}
            {/*                Implementação e suporte a aplicações multiplataforma utilizando JavaScript e React.js ao lado de Node.js, Java ou Python.*/}
            {/*                Além disso estudo a implementação de objetos e elementos tipados com TypeScript.*/}
            {/*            </Paragraph>*/}
            {/*        </Card>*/}
            {/*        <Card title="UI & UX Design" textColor="#222" bgColor="#FFF" srcImage={path_SkillIHC} >*/}
            {/*            <Paragraph>*/}
            {/*                Manter uma experiência positiva ao usuário possibilita o mapeamento de pontos focais e a priorização de recursos, garantindo a alavancagem*/}
            {/*                natural do produto expandindo a ótica de solução e definição dos objetivos.*/}
            {/*            </Paragraph>*/}
            {/*        </Card>*/}
            {/*    </Skills>*/}
            {/*</FlexLayoutRow>*/}
        </>
    );
}

export default Home;

// src/app/views/home/shared/components/home.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.scss']
})
export class HomeComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
    console.log("[HomeComponent] Init")
  }

}

<h3>Michel Camargo</h3>

<span>
  Implementação e suporte a aplicações multiplataforma utilizando JavaScript e React.js ao lado de Node.js, Java ou Python.
  Além disso estudo a implementação de objetos e elementos tipados com TypeScript.
</span>

<span>
  Manter uma experiência positiva ao usuário possibilita o mapeamento de pontos focais e a priorização de recursos, garantindo a alavancagem
  natural do produto expandindo a ótica de solução e definição dos objetivos.
</span>

<p>Acadêmico de Tecnologia em Sistemas para Internet pela Universidade Tecnológica Federal do Paraná </p>
<p>Desenvolvedor de aplicações Web com foco na experiência do usuário e facilitação do uso e aprendizado</p>
<p>Aficionado por tecnologia e design de interação, além de entusiasta do audiovisual e apreciador de boas artes</p>
